name: rtcloud_av1
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - awscli=1.25.28
  - babel=2.9.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - boto3=1.24.28
  - botocore=1.27.28
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - cctools_osx-64=949.0.1
  - certifi=2022.9.14
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - clang=12.0.0
  - clang-12=12.0.0
  - clangxx=12.0.0
  - clangxx_osx-64
  - colorama=0.4.4
  - compiler-rt=12.0.0
  - compiler-rt_osx-64=12.0.0
  - cryptography=37.0.1
  - cycler=0.11.0
  - cython=0.29.32
  - dcm2niix=1.0.20220720
  - debugpy=1.5.1
  - defusedxml=0.7.1
  - docutils=0.16
  - entrypoints=0.4
  - flake8=4.0.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - indexed_gzip=1.7.0
  - iniconfig=1.1.1
  - ipykernel=6.15.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.3
  - jupyter_core=4.11.1
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.15.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld64_osx-64=530
  - ldid=2.1.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang-cpp12=12.0.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.3
  - libgfortran
  - libiconv=1.16
  - libllvm12=12.0.0
  - libllvm14=14.0.6
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.12
  - llvm-meta=7.0.0
  - llvm-openmp
  - llvm-tools=12.0.0
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=0.8.4
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.2
  - munkres=1.1.4
  - mypy=0.910
  - mypy_extensions=0.4.3
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.6.3
  - nibabel=4.0.2
  - nilearn=0.9.2
  - nitime=0.9
  - nodejs=10.13.0
  - nomkl=3.0
  - notebook=6.4.12
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openmp=7.0.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.8.3
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - pluggy=1.0.0
  - plumbum=1.7.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - py=1.11.0
  - pyasn1=0.4.8
  - pybind11=2.9.2
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydicom=2.3.0
  - pyflakes=2.4.0
  - pygments=2.11.2
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.6.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.7.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.7
  - pytz=2022.1
  - pywin32-on-windows=0.1.0
  - pyyaml=5.4.1
  - pyzmq=23.2.0
  - qt=5.6.3
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - readline=8.1.2
  - requests=2.28.1
  - rpyc=5.0.1
  - rsa=4.7.2
  - s3transfer=0.6.0
  - scikit-learn=0.22.1
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=63.4.1
  - sip=4.18.1
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.39.3
  - statsmodels=0.13.2
  - tapi=1000.10.8
  - terminado=0.13.1
  - testpath=0.6.0
  - theano=1.0.5
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wsaccel=0.6.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - arabic-reshaper
    - astor
    - astunparse
    - bids-validator
    - brainiak
    - click
    - decorator
    - deprecated
    - docopt
    - dukpy
    - esprima
    - et-xmlfile
    - formulaic
    - freetype-py
    - future
    - gevent
    - gitdb
    - gitpython
    - glfw
    - graphtools
    - greenlet
    - imageio
    - imageio-ffmpeg
    - inotify
    - interface-meta
    - javascripthon
    - json-tricks
    - moviepy
    - msgpack
    - msgpack-numpy
    - nose
    - num2words
    - openpyxl
    - phate
    - proglog
    - psychopy
    - psychtoolbox
    - pybids
    - pygame
    - pyglet
    - pygsp
    - pyo
    - pyobjc
    - pyobjc-core
    - pyobjc-framework-accessibility
    - pyobjc-framework-accounts
    - pyobjc-framework-addressbook
    - pyobjc-framework-adservices
    - pyobjc-framework-adsupport
    - pyobjc-framework-applescriptkit
    - pyobjc-framework-applescriptobjc
    - pyobjc-framework-applicationservices
    - pyobjc-framework-apptrackingtransparency
    - pyobjc-framework-audiovideobridging
    - pyobjc-framework-authenticationservices
    - pyobjc-framework-automaticassessmentconfiguration
    - pyobjc-framework-automator
    - pyobjc-framework-avfoundation
    - pyobjc-framework-avkit
    - pyobjc-framework-businesschat
    - pyobjc-framework-calendarstore
    - pyobjc-framework-callkit
    - pyobjc-framework-cfnetwork
    - pyobjc-framework-classkit
    - pyobjc-framework-cloudkit
    - pyobjc-framework-cocoa
    - pyobjc-framework-collaboration
    - pyobjc-framework-colorsync
    - pyobjc-framework-contacts
    - pyobjc-framework-contactsui
    - pyobjc-framework-coreaudio
    - pyobjc-framework-coreaudiokit
    - pyobjc-framework-corebluetooth
    - pyobjc-framework-coredata
    - pyobjc-framework-corehaptics
    - pyobjc-framework-corelocation
    - pyobjc-framework-coremedia
    - pyobjc-framework-coremediaio
    - pyobjc-framework-coremidi
    - pyobjc-framework-coreml
    - pyobjc-framework-coremotion
    - pyobjc-framework-coreservices
    - pyobjc-framework-corespotlight
    - pyobjc-framework-coretext
    - pyobjc-framework-corewlan
    - pyobjc-framework-cryptotokenkit
    - pyobjc-framework-datadetection
    - pyobjc-framework-devicecheck
    - pyobjc-framework-dictionaryservices
    - pyobjc-framework-discrecording
    - pyobjc-framework-discrecordingui
    - pyobjc-framework-diskarbitration
    - pyobjc-framework-dvdplayback
    - pyobjc-framework-eventkit
    - pyobjc-framework-exceptionhandling
    - pyobjc-framework-executionpolicy
    - pyobjc-framework-externalaccessory
    - pyobjc-framework-fileprovider
    - pyobjc-framework-fileproviderui
    - pyobjc-framework-findersync
    - pyobjc-framework-fsevents
    - pyobjc-framework-gamecenter
    - pyobjc-framework-gamecontroller
    - pyobjc-framework-gamekit
    - pyobjc-framework-gameplaykit
    - pyobjc-framework-imagecapturecore
    - pyobjc-framework-imserviceplugin
    - pyobjc-framework-inputmethodkit
    - pyobjc-framework-installerplugins
    - pyobjc-framework-instantmessage
    - pyobjc-framework-intents
    - pyobjc-framework-intentsui
    - pyobjc-framework-iosurface
    - pyobjc-framework-ituneslibrary
    - pyobjc-framework-kernelmanagement
    - pyobjc-framework-latentsemanticmapping
    - pyobjc-framework-launchservices
    - pyobjc-framework-libdispatch
    - pyobjc-framework-linkpresentation
    - pyobjc-framework-localauthentication
    - pyobjc-framework-localauthenticationembeddedui
    - pyobjc-framework-mailkit
    - pyobjc-framework-mapkit
    - pyobjc-framework-mediaaccessibility
    - pyobjc-framework-medialibrary
    - pyobjc-framework-mediaplayer
    - pyobjc-framework-mediatoolbox
    - pyobjc-framework-metal
    - pyobjc-framework-metalkit
    - pyobjc-framework-metalperformanceshaders
    - pyobjc-framework-metalperformanceshadersgraph
    - pyobjc-framework-metrickit
    - pyobjc-framework-mlcompute
    - pyobjc-framework-modelio
    - pyobjc-framework-multipeerconnectivity
    - pyobjc-framework-naturallanguage
    - pyobjc-framework-netfs
    - pyobjc-framework-network
    - pyobjc-framework-networkextension
    - pyobjc-framework-notificationcenter
    - pyobjc-framework-opendirectory
    - pyobjc-framework-osakit
    - pyobjc-framework-oslog
    - pyobjc-framework-passkit
    - pyobjc-framework-pencilkit
    - pyobjc-framework-photos
    - pyobjc-framework-photosui
    - pyobjc-framework-preferencepanes
    - pyobjc-framework-pushkit
    - pyobjc-framework-quartz
    - pyobjc-framework-quicklookthumbnailing
    - pyobjc-framework-replaykit
    - pyobjc-framework-safariservices
    - pyobjc-framework-scenekit
    - pyobjc-framework-screencapturekit
    - pyobjc-framework-screensaver
    - pyobjc-framework-screentime
    - pyobjc-framework-scriptingbridge
    - pyobjc-framework-searchkit
    - pyobjc-framework-security
    - pyobjc-framework-securityfoundation
    - pyobjc-framework-securityinterface
    - pyobjc-framework-servicemanagement
    - pyobjc-framework-shazamkit
    - pyobjc-framework-social
    - pyobjc-framework-soundanalysis
    - pyobjc-framework-speech
    - pyobjc-framework-spritekit
    - pyobjc-framework-storekit
    - pyobjc-framework-syncservices
    - pyobjc-framework-systemconfiguration
    - pyobjc-framework-systemextensions
    - pyobjc-framework-uniformtypeidentifiers
    - pyobjc-framework-usernotifications
    - pyobjc-framework-usernotificationsui
    - pyobjc-framework-videosubscriberaccount
    - pyobjc-framework-videotoolbox
    - pyobjc-framework-virtualization
    - pyobjc-framework-vision
    - pyobjc-framework-webkit
    - pyopengl
    - pyserial
    - python-bidi
    - python-gitlab
    - python-vlc
    - questplus
    - requests-toolbelt
    - s-gd2
    - scprep
    - seaborn
    - smmap
    - sounddevice
    - soundfile
    - sqlalchemy
    - tables
    - tasklogger
    - tqdm
    - ujson
    - watchdog
    - wrapt
    - wxpython
    - xarray
    - xlrd
    - zope-event
    - zope-interface
